### ISSUE TITLE
Devices are unable to be accessed after short period of time

### ISSUE THREAD

**Issue by nickman2025** [mmillmor/AmazonEcho-to-Vera#1]
Echo can't control devices after a short period of time using Amazon's OAuth2 server directly. Do you have an in depth walk through for creating your own server as it appears Amazon won't fix the issue on their end?

**Comment by mmillmor** [comment]
That's not my experience on the Amazon OAuth, but yes, there are detailed instructions on creating your own OAuth in the main README file.
